### ISSUE TITLE
Got deprecation message for Minitest::Test but minitest has no `test` method

### ISSUE THREAD

**Issue by mishina2228** [svenfuchs/test_declarative#20]
```ruby
require 'minitest/autorun'
require 'test_declarative'

class MyTestUnit < MiniTest::Test
  test "your test description" do
    assert true
  end
end
```

```
$ ruby mytest_mini.rb
test_declarative is deprecated for Minitest::Unit::TestCase
test_declarative is deprecated for Minitest::Test
Run options: --seed 48646

# Running:

.

Finished in 0.005164s, 193.6620 runs/s, 193.6620 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

If `require 'test_declarative'` is commented out here:
```
$ ruby mytest_mini.rb
mytest_mini.rb:5:in `test': unknown command 'y' (ArgumentError)
        from mytest_mini.rb:5:in `<class:MyTestUnit>'
        from mytest_mini.rb:4:in `<main>'
```

I think it is because `test` method is defined first in `Module`.
https://github.com/svenfuchs/test_declarative/blob/d0c26d1e5bcd9880bd4a758ce462eb8fd31e2928/lib/test_declarative.rb#L1-L4

The following are used.
- minitest (5.15.0)
- test_declarative (0.0.6)

**Comment by mishina2228** [comment]
These warnings can be seen in the CI on [ruby-i18n/i18n](https://github.com/ruby-i18n/i18n).
https://github.com/ruby-i18n/i18n/runs/5191721776?check_suite_focus=true
![image](https://user-images.githubusercontent.com/32959831/160268832-0b25ad0e-a269-48f6-a1a5-203052d35a72.png)

**Comment by junaruga** [comment]
I checked the deprecated messages are printed on the current latest master branch 4c0ccc6f649f33f76772a826e6afd367b143cd66 on my local.

```
$ pwd
/home/jaruga/git/test_declarative

$ bundle install --standalone

$ bundle exec ruby mytest_mini.rb
test_declarative is deprecated for Minitest::Unit::TestCase
test_declarative is deprecated for Minitest::Test
Run options: --seed 5597

# Running:

.

Finished in 0.000541s, 1848.0402 runs/s, 1848.0402 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

I also checked the deprecated messages are not printed on this PR on my local.

```
$ bundle exec ruby mytest_mini.rb
Run options: --seed 28356

# Running:

.

Finished in 0.000959s, 1042.2118 runs/s, 1042.2118 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by junaruga** [comment]
> I think it is because we have defined test method in Module first.

What I don't understand is why `Module` class is defined as a first element of the `targets` currently. This issue did not happen in old Rubies?

@svenfuchs Do you have any comments on this?

**Comment by mishina2228** [comment]
> This issue did not happen in old Rubies?

At least as of Ruby 1.9.3, these deprecated warnings are printed.

https://github.com/mishina2228/test_declarative/runs/5755153567?check_suite_focus=true
![image](https://user-images.githubusercontent.com/32959831/160849954-9af217aa-1288-4319-8324-ce8ba5ab4a4d.png)

I could not check for versions prior to 1.9.3 because ruby/setup-ruby does not support them. 😅
